apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: misp-core-claim0
  name: misp-core-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path
