apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: misp-modules
  name: misp-modules
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: misp-modules
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: misp-modules
    spec:
      containers:
        - image: ghcr.io/misp/misp-docker/misp-modules:latest
          name: misp-modules
          livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
      restartPolicy: Always
