apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
    healthcheck.path: /users/heartbeat
    healthcheck.port: "443"
  labels:
    io.kompose.service: misp-core
  name: misp-core
spec:
  type: NodePort # Use NodePort to expose the service externally
  ports:
    - name: "80"
      port: 80
      targetPort: 80
      nodePort: 32080  # Ensure this port is free
    - name: "443"
      port: 443
      targetPort: 443
      nodePort: 32443  # Ensure this port is free
  externalIPs:
    - 129.114.26.122
  selector:
    io.kompose.service: misp-core
