apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: misp-core-claim4
  name: misp-core-claim4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path
