apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: misp-core-claim1
  name: misp-core-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
